---
- name: "install apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy code to backend server
  copy:
    src: "/home/circleci/project/backend.tar.gz"
    dest: "/home/ubuntu/"

- name: Install dependencies and create build on backend server
  shell: |
    cd /home/ubuntu/
    #sudo apt-get install unzip
    sudo apt-get install tar
    #unzip backend.zip
    tar -xvzf backend.tar.gz -C /home/ubuntu/backend
    cd backend
    npm i
    npm run build

- name: Executing node
  environment:
    ENVIRONMENT: "production"
    TYPEORM_CONNECTION: "postgres"
    TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start