---
- name: "install apt packages."
  become: yes
  apt:
    update_cache: yes

# - name: "upgrade packages"
#   become: yes
#   apt:
#     upgrade: yes

# - name: remove dependencies that are no longer required
#   become: yes
#   apt:
#     autoremove: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy code to backend server
  copy:
    src: "/home/circleci/project/backend.tar.gz"
    dest: "/home/ubuntu/"

- name: Install dependencies and create build on backend server
  shell: |
    cd /home/ubuntu/
    #sudo apt-get install unzip
    sudo apt-get install tar
    #unzip backend.zip
    tar -xvzf backend.tar.gz -C /home/ubuntu/backend
    # cd dist
    npm i
    npm run build

- name: Executing node
  shell: |
    cd /home/ubuntu/backend
    pm2 start --name backend